### ISSUE TITLE
No Operation named [pnet/input] in the Graph

### ISSUE THREAD

**Issue by bewithme** [waltyou/face-detect#1]
java.lang.IllegalArgumentException: No Operation named [pnet/input] in the Graph
	at org.tensorflow.Session$Runner.operationByName(Session.java:384)
	at org.tensorflow.Session$Runner.parseOutput(Session.java:398)
	at org.tensorflow.Session$Runner.feed(Session.java:132)
	at com.walt.face.mtcnn.Mtcnn.predict(Mtcnn.java:143)
	at com.walt.face.mtcnn.Mtcnn.pNetForword(Mtcnn.java:117)
	at com.walt.face.mtcnn.Mtcnn.pNet(Mtcnn.java:102)
	at com.walt.face.mtcnn.Mtcnn.detectFaces(Mtcnn.java:76)

**Comment by waltyou** [comment]
Seems there not have 'pnet/input' operation in your pb file. Please use the pb file from [here](https://github.com/cayden/UVCCamera/blob/master/usbCameraTest/src/main/assets/mtcnn_freezed_model.pb).

You can use blow code to list all operations name in your pb file. And check if 'pnet/input' exist.
```java
Graph graph = TensorflowUtils.getGraph("pb_file_path");
for (Iterator<Operation> it = graph.operations(); it.hasNext(); ) {
    Operation o = it.next();
    System.out.println(o.name());
}
```

**Comment by bewithme** [comment]
do I have to run it on GPU? I download the model and run it again

2020-08-20 16:40:29.899809: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-20 16:40:29.910232: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fec650a3ae0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-20 16:40:29.910265: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[2020-08-20 16:40:30]【1】PNet generate candidate boxes...
[2020-08-20 16:40:30]currentFaceSize 5.0
java.lang.IllegalArgumentException: No Operation named [pnet/input] in the Graph
	at org.tensorflow.Session$Runner.operationByName(Session.java:384)
	at org.tensorflow.Session$Runner.parseOutput(Session.java:398)
	at org.tensorflow.Session$Runner.feed(Session.java:132)
	at com.walt.face.mtcnn.Mtcnn.predict(Mtcnn.java:152)
	at com.walt.face.mtcnn.Mtcnn.pNetForword(Mtcnn.java:126)
	at com.walt.face.mtcnn.Mtcnn.pNet(Mtcnn.java:111)
	at com.walt.face.mtcnn.Mtcnn.detectFaces(Mtcnn.java:85)

**Comment by waltyou** [comment]
No. 
Use blow code to list all operation name. You can add them after [here](https://github.com/waltyou/face-detect/blob/master/src/main/java/com/walt/face/mtcnn/Mtcnn.java#L52):
```java
for (Iterator<Operation> it = graph.operations(); it.hasNext(); ) {
    Operation o = it.next();
    System.out.println(o.name());
}
```

**Comment by bewithme** [comment]
pnet/input
pnet/conv1/weights
pnet/conv1/weights/read
pnet/conv1/Conv2D
pnet/conv1/biases
pnet/conv1/biases/read
pnet/conv1/BiasAdd
pnet/PReLU1/alpha
pnet/PReLU1/alpha/read
pnet/PReLU1/Relu
pnet/PReLU1/Neg
pnet/PReLU1/Relu_1
pnet/PReLU1/Neg_1
pnet/PReLU1/Mul
pnet/PReLU1/add
pnet/pool1
pnet/conv2/weights
pnet/conv2/weights/read
pnet/conv2/Conv2D
pnet/conv2/biases
pnet/conv2/biases/read
pnet/conv2/BiasAdd
pnet/PReLU2/alpha
pnet/PReLU2/alpha/read
pnet/PReLU2/Relu
pnet/PReLU2/Neg
pnet/PReLU2/Relu_1
pnet/PReLU2/Neg_1
pnet/PReLU2/Mul
pnet/PReLU2/add
pnet/conv3/weights
pnet/conv3/weights/read
pnet/conv3/Conv2D
pnet/conv3/biases
pnet/conv3/biases/read
pnet/conv3/BiasAdd
pnet/PReLU3/alpha
pnet/PReLU3/alpha/read
pnet/PReLU3/Relu
pnet/PReLU3/Neg
pnet/PReLU3/Relu_1
pnet/PReLU3/Neg_1
pnet/PReLU3/Mul
pnet/PReLU3/add
pnet/conv4-1/weights
pnet/conv4-1/weights/read
pnet/conv4-1/Conv2D
pnet/conv4-1/biases
pnet/conv4-1/biases/read
pnet/conv4-1/BiasAdd
pnet/Max/reduction_indices
pnet/Max
pnet/sub
pnet/Exp
pnet/Sum/reduction_indices
pnet/Sum
pnet/prob1
pnet/conv4-2/weights
pnet/conv4-2/weights/read
pnet/conv4-2/Conv2D
pnet/conv4-2/biases
pnet/conv4-2/biases/read
pnet/conv4-2/BiasAdd
rnet/input
rnet/conv1/weights
rnet/conv1/weights/read
rnet/conv1/Conv2D
rnet/conv1/biases
rnet/conv1/biases/read
rnet/conv1/BiasAdd
rnet/prelu1/alpha
rnet/prelu1/alpha/read
rnet/prelu1/Relu
rnet/prelu1/Neg
rnet/prelu1/Relu_1
rnet/prelu1/Neg_1
rnet/prelu1/Mul
rnet/prelu1/add
rnet/pool1
rnet/conv2/weights
rnet/conv2/weights/read
rnet/conv2/Conv2D
rnet/conv2/biases
rnet/conv2/biases/read
rnet/conv2/BiasAdd
rnet/prelu2/alpha
rnet/prelu2/alpha/read
rnet/prelu2/Relu
rnet/prelu2/Neg
rnet/prelu2/Relu_1
rnet/prelu2/Neg_1
rnet/prelu2/Mul
rnet/prelu2/add
rnet/pool2
rnet/conv3/weights
rnet/conv3/weights/read
rnet/conv3/Conv2D
rnet/conv3/biases
rnet/conv3/biases/read
rnet/conv3/BiasAdd
rnet/prelu3/alpha
rnet/prelu3/alpha/read
rnet/prelu3/Relu
rnet/prelu3/Neg
rnet/prelu3/Relu_1
rnet/prelu3/Neg_1
rnet/prelu3/Mul
rnet/prelu3/add
rnet/conv4/Reshape/shape
rnet/conv4/Reshape
rnet/conv4/weights
rnet/conv4/weights/read
rnet/conv4/biases
rnet/conv4/biases/read
rnet/conv4/conv4/MatMul
rnet/conv4/conv4
rnet/prelu4/alpha
rnet/prelu4/alpha/read
rnet/prelu4/Relu
rnet/prelu4/Neg
rnet/prelu4/Relu_1
rnet/prelu4/Neg_1
rnet/prelu4/Mul
rnet/prelu4/add
rnet/conv5-1/weights
rnet/conv5-1/weights/read
rnet/conv5-1/biases
rnet/conv5-1/biases/read
rnet/conv5-1/conv5-1/MatMul
rnet/conv5-1/conv5-1
rnet/Max/reduction_indices
rnet/Max
rnet/sub
rnet/Exp
rnet/Sum/reduction_indices
rnet/Sum
rnet/prob1
rnet/conv5-2/weights
rnet/conv5-2/weights/read
rnet/conv5-2/biases
rnet/conv5-2/biases/read
rnet/conv5-2/conv5-2/MatMul
rnet/conv5-2/conv5-2
onet/input
onet/conv1/weights
onet/conv1/weights/read
onet/conv1/Conv2D
onet/conv1/biases
onet/conv1/biases/read
onet/conv1/BiasAdd
onet/prelu1/alpha
onet/prelu1/alpha/read
onet/prelu1/Relu
onet/prelu1/Neg
onet/prelu1/Relu_1
onet/prelu1/Neg_1
onet/prelu1/Mul
onet/prelu1/add
onet/pool1
onet/conv2/weights
onet/conv2/weights/read
onet/conv2/Conv2D
onet/conv2/biases
onet/conv2/biases/read
onet/conv2/BiasAdd
onet/prelu2/alpha
onet/prelu2/alpha/read
onet/prelu2/Relu
onet/prelu2/Neg
onet/prelu2/Relu_1
onet/prelu2/Neg_1
onet/prelu2/Mul
onet/prelu2/add
onet/pool2
onet/conv3/weights
onet/conv3/weights/read
onet/conv3/Conv2D
onet/conv3/biases
onet/conv3/biases/read
onet/conv3/BiasAdd
onet/prelu3/alpha
onet/prelu3/alpha/read
onet/prelu3/Relu
onet/prelu3/Neg
onet/prelu3/Relu_1
onet/prelu3/Neg_1
onet/prelu3/Mul
onet/prelu3/add
onet/pool3
onet/conv4/weights
onet/conv4/weights/read
onet/conv4/Conv2D
onet/conv4/biases
onet/conv4/biases/read
onet/conv4/BiasAdd
onet/prelu4/alpha
onet/prelu4/alpha/read
onet/prelu4/Relu
onet/prelu4/Neg
onet/prelu4/Relu_1
onet/prelu4/Neg_1
onet/prelu4/Mul
onet/prelu4/add
onet/conv5/Reshape/shape
onet/conv5/Reshape
onet/conv5/weights
onet/conv5/weights/read
onet/conv5/biases
onet/conv5/biases/read
onet/conv5/conv5/MatMul
onet/conv5/conv5
onet/prelu5/alpha
onet/prelu5/alpha/read
onet/prelu5/Relu
onet/prelu5/Neg
onet/prelu5/Relu_1
onet/prelu5/Neg_1
onet/prelu5/Mul
onet/prelu5/add
onet/conv6-1/weights
onet/conv6-1/weights/read
onet/conv6-1/biases
onet/conv6-1/biases/read
onet/conv6-1/conv6-1/MatMul
onet/conv6-1/conv6-1
onet/Max/reduction_indices
onet/Max
onet/sub
onet/Exp
onet/Sum/reduction_indices
onet/Sum
onet/prob1
onet/conv6-2/weights
onet/conv6-2/weights/read
onet/conv6-2/biases
onet/conv6-2/biases/read
onet/conv6-2/conv6-2/MatMul
onet/conv6-2/conv6-2
onet/conv6-3/weights
onet/conv6-3/weights/read
onet/conv6-3/biases
onet/conv6-3/biases/read
onet/conv6-3/conv6-3/MatMul
onet/conv6-3/conv6-3

this is all ops in grah

**Comment by waltyou** [comment]
Wired. What the P_NET_IN_NAME value in your Mtcnn.java ? It supporse to be  "pnet/input:0".

**Comment by bewithme** [comment]
Yes it is pnet/input:0 , I don’t change it.

**Comment by bewithme** [comment]
can you rerun your code can check it ? I really need your help.

**Comment by waltyou** [comment]
I know it. Please run ' rm /tmp/mtcnn_freezed_model.pb' in your shell. The `ResourceUtils.getResourceFilePath` function will cache the pb file under '/tmp'. So you are still using the first pb file which not have [pnet/input] layer.

**Comment by bewithme** [comment]
when I run the command you afford , show error bellow

empty streaming
java.lang.NullPointerException
	at com.walt.face.utils.ResourceUtils.getResourceFilePath(ResourceUtils.java:36)
	at com.walt.face.mtcnn.Mtcnn.<init>(Mtcnn.java:57)
	at com.walt.face.mtcnn.Test.main(Test.java:14)

**Comment by bewithme** [comment]
can you add my wechat  : italybaby for discussing

**Comment by waltyou** [comment]
Move the download pb file to '/tmp'.
